# Generated by Django 5.1.1 on 2024-10-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('pokedex_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('abilities', models.JSONField()),
                ('sprites', models.JSONField()),
                ('types', models.JSONField()),
            ],
        ),
    ]
